"""Add media_url column to messages table

Revision ID: 6d6a176619fc
Revises: 
Create Date: 2025-10-03 10:59:50.859867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d6a176619fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ghl_locations_active'), table_name='ghl_locations', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_ghl_locations_company'), table_name='ghl_locations')
    op.drop_index(op.f('idx_ghl_locations_whatsapp'), table_name='ghl_locations', postgresql_where='(has_whatsapp = true)')
    op.drop_table('ghl_locations')
    op.drop_index(op.f('idx_processed_webhooks_location'), table_name='processed_webhooks')
    op.drop_index(op.f('idx_processed_webhooks_ttl'), table_name='processed_webhooks')
    op.drop_table('processed_webhooks')
    op.drop_index(op.f('idx_messages_campaign'), table_name='messages')
    op.drop_index(op.f('idx_messages_campaign_sent'), table_name='messages')
    op.drop_index(op.f('idx_messages_ghl_conversation'), table_name='messages')
    op.drop_index(op.f('idx_messages_ghl_message_id'), table_name='messages', postgresql_where='(ghl_message_id IS NOT NULL)')
    op.drop_index(op.f('idx_messages_recipient'), table_name='messages')
    op.drop_index(op.f('idx_messages_sent_at'), table_name='messages')
    op.drop_index(op.f('idx_messages_status'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('idx_ghl_oauth_tokens_expiry'), table_name='ghl_oauth_tokens')
    op.drop_index(op.f('idx_ghl_oauth_tokens_location'), table_name='ghl_oauth_tokens')
    op.drop_table('ghl_oauth_tokens')
    op.drop_index(op.f('idx_ghl_users_active'), table_name='ghl_users')
    op.drop_index(op.f('idx_ghl_users_location'), table_name='ghl_users')
    op.drop_index(op.f('idx_ghl_users_user_id'), table_name='ghl_users')
    op.drop_table('ghl_users')
    op.drop_index(op.f('idx_campaigns_created_at'), table_name='campaigns')
    op.drop_index(op.f('idx_campaigns_ghl_location'), table_name='campaigns')
    op.drop_index(op.f('idx_campaigns_ghl_user'), table_name='campaigns')
    op.drop_index(op.f('idx_campaigns_scheduled'), table_name='campaigns', postgresql_where='(scheduled_time IS NOT NULL)')
    op.drop_index(op.f('idx_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('idx_campaigns_user'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('idx_ghl_conversations_contact'), table_name='ghl_conversations')
    op.drop_index(op.f('idx_ghl_conversations_location'), table_name='ghl_conversations')
    op.drop_index(op.f('idx_ghl_conversations_phone'), table_name='ghl_conversations')
    op.drop_index(op.f('idx_ghl_conversations_unique'), table_name='ghl_conversations')
    op.drop_table('ghl_conversations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ghl_conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ghl_conversation_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ghl_location_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ghl_contact_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('contact_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_message_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_message_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('unread_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ghl_location_id'], ['ghl_locations.ghl_location_id'], name=op.f('ghl_conversations_ghl_location_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ghl_conversations_pkey')),
    sa.UniqueConstraint('ghl_conversation_id', name=op.f('ghl_conversations_ghl_conversation_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_ghl_conversations_unique'), 'ghl_conversations', ['ghl_location_id', 'ghl_contact_id'], unique=True)
    op.create_index(op.f('idx_ghl_conversations_phone'), 'ghl_conversations', ['contact_phone'], unique=False)
    op.create_index(op.f('idx_ghl_conversations_location'), 'ghl_conversations', ['ghl_location_id'], unique=False)
    op.create_index(op.f('idx_ghl_conversations_contact'), 'ghl_conversations', ['ghl_contact_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('campaigns_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('sending_speed', sa.VARCHAR(length=20), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=True),
    sa.Column('schedule_type', sa.VARCHAR(length=50), server_default=sa.text("'immediate'::character varying"), autoincrement=False, nullable=True),
    sa.Column('ghl_location_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ghl_location_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ghl_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ghl_user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('scheduled_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Timestamp for scheduled campaign execution (NULL for immediate campaigns)'),
    sa.Column('paused_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ghl_user_ids', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='campaigns_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_campaigns_user'), 'campaigns', ['ghl_user_id'], unique=False)
    op.create_index(op.f('idx_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index(op.f('idx_campaigns_scheduled'), 'campaigns', ['scheduled_time', 'status'], unique=False, postgresql_where='(scheduled_time IS NOT NULL)')
    op.create_index(op.f('idx_campaigns_ghl_user'), 'campaigns', ['ghl_user_id'], unique=False)
    op.create_index(op.f('idx_campaigns_ghl_location'), 'campaigns', ['ghl_location_id'], unique=False)
    op.create_index(op.f('idx_campaigns_created_at'), 'campaigns', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('ghl_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ghl_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ghl_location_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ghl_location_id'], ['ghl_locations.ghl_location_id'], name=op.f('ghl_users_ghl_location_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ghl_users_pkey')),
    sa.UniqueConstraint('ghl_user_id', name=op.f('ghl_users_ghl_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_ghl_users_user_id'), 'ghl_users', ['ghl_user_id'], unique=False)
    op.create_index(op.f('idx_ghl_users_location'), 'ghl_users', ['ghl_location_id'], unique=False)
    op.create_index(op.f('idx_ghl_users_active'), 'ghl_users', ['is_active'], unique=False)
    op.create_table('ghl_oauth_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ghl_location_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('access_token_encrypted', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_encrypted', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('token_type', sa.VARCHAR(length=20), server_default=sa.text("'Bearer'::character varying"), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ghl_location_id'], ['ghl_locations.ghl_location_id'], name=op.f('ghl_oauth_tokens_ghl_location_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ghl_oauth_tokens_pkey')),
    sa.UniqueConstraint('ghl_location_id', name=op.f('ghl_oauth_tokens_ghl_location_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_ghl_oauth_tokens_location'), 'ghl_oauth_tokens', ['ghl_location_id'], unique=False)
    op.create_index(op.f('idx_ghl_oauth_tokens_expiry'), 'ghl_oauth_tokens', ['expires_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipient_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ghl_conversation_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ghl_message_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ghl_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('messages_campaign_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('idx_messages_status'), 'messages', ['status'], unique=False)
    op.create_index(op.f('idx_messages_sent_at'), 'messages', ['sent_at'], unique=False)
    op.create_index(op.f('idx_messages_recipient'), 'messages', ['recipient_phone'], unique=False)
    op.create_index(op.f('idx_messages_ghl_message_id'), 'messages', ['ghl_message_id'], unique=True, postgresql_where='(ghl_message_id IS NOT NULL)')
    op.create_index(op.f('idx_messages_ghl_conversation'), 'messages', ['ghl_conversation_id'], unique=False)
    op.create_index(op.f('idx_messages_campaign_sent'), 'messages', ['campaign_id', sa.literal_column('sent_at DESC')], unique=False)
    op.create_index(op.f('idx_messages_campaign'), 'messages', ['campaign_id'], unique=False)
    op.create_table('processed_webhooks',
    sa.Column('webhook_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ghl_location_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('payload_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('webhook_id', name=op.f('processed_webhooks_pkey'))
    )
    op.create_index(op.f('idx_processed_webhooks_ttl'), 'processed_webhooks', ['processed_at'], unique=False)
    op.create_index(op.f('idx_processed_webhooks_location'), 'processed_webhooks', ['ghl_location_id'], unique=False)
    op.create_table('ghl_locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ghl_location_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('has_whatsapp', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('whatsapp_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('whatsapp_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ghl_locations_pkey')),
    sa.UniqueConstraint('ghl_location_id', name=op.f('ghl_locations_ghl_location_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_ghl_locations_whatsapp'), 'ghl_locations', ['has_whatsapp'], unique=False, postgresql_where='(has_whatsapp = true)')
    op.create_index(op.f('idx_ghl_locations_company'), 'ghl_locations', ['company_id'], unique=False)
    op.create_index(op.f('idx_ghl_locations_active'), 'ghl_locations', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    # ### end Alembic commands ###
