"""initial_schema

Revision ID: eb03c3cc8781
Revises: 
Create Date: 2026-04-10 15:42:54.580477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb03c3cc8781'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('contacts_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('campaigns', sa.Column('messages_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaigns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaigns', 'scheduled_time',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp for scheduled campaign execution (NULL for immediate campaigns)',
               existing_nullable=True)
    op.drop_index('idx_campaigns_ghl_user', table_name='campaigns')
    op.drop_index('idx_campaigns_scheduled', table_name='campaigns', postgresql_where='(scheduled_time IS NOT NULL)')
    op.drop_index('idx_campaigns_user', table_name='campaigns')
    op.drop_index('idx_campaigns_created_at', table_name='campaigns')
    op.create_index('idx_campaigns_created_at', 'campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaigns_ghl_location_id'), 'campaigns', ['ghl_location_id'], unique=False)
    op.create_index(op.f('ix_campaigns_ghl_user_id'), 'campaigns', ['ghl_user_id'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_foreign_key(None, 'campaigns', 'ghl_locations', ['ghl_location_id'], ['ghl_location_id'], ondelete='RESTRICT')
    op.alter_column('ghl_conversations', 'unread_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ghl_conversations', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('ghl_conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ghl_conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('ghl_conversations_ghl_conversation_id_key', 'ghl_conversations', type_='unique')
    op.drop_index('idx_ghl_conversations_unique', table_name='ghl_conversations')
    op.create_unique_constraint('idx_ghl_conversations_unique', 'ghl_conversations', ['ghl_location_id', 'ghl_contact_id'])
    op.create_index(op.f('ix_ghl_conversations_contact_phone'), 'ghl_conversations', ['contact_phone'], unique=False)
    op.create_index(op.f('ix_ghl_conversations_ghl_contact_id'), 'ghl_conversations', ['ghl_contact_id'], unique=False)
    op.create_index(op.f('ix_ghl_conversations_ghl_conversation_id'), 'ghl_conversations', ['ghl_conversation_id'], unique=True)
    op.create_index(op.f('ix_ghl_conversations_ghl_location_id'), 'ghl_conversations', ['ghl_location_id'], unique=False)
    op.alter_column('ghl_locations', 'has_whatsapp',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('ghl_locations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('ghl_locations', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('ghl_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ghl_locations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # Use CASCADE because ghl_oauth_tokens, ghl_conversations, and ghl_users have FKs
    # referencing this unique constraint; we recreate them explicitly below.
    op.execute('ALTER TABLE ghl_locations DROP CONSTRAINT ghl_locations_ghl_location_id_key CASCADE')
    op.create_index(op.f('ix_ghl_locations_company_id'), 'ghl_locations', ['company_id'], unique=False)
    op.create_index(op.f('ix_ghl_locations_ghl_location_id'), 'ghl_locations', ['ghl_location_id'], unique=True)
    # Recreate FKs dropped by CASCADE above
    op.create_foreign_key('ghl_oauth_tokens_ghl_location_id_fkey', 'ghl_oauth_tokens', 'ghl_locations', ['ghl_location_id'], ['ghl_location_id'])
    op.create_foreign_key('ghl_conversations_ghl_location_id_fkey', 'ghl_conversations', 'ghl_locations', ['ghl_location_id'], ['ghl_location_id'])
    op.create_foreign_key('ghl_users_ghl_location_id_fkey', 'ghl_users', 'ghl_locations', ['ghl_location_id'], ['ghl_location_id'])
    op.alter_column('ghl_oauth_tokens', 'token_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Bearer'::character varying"))
    op.alter_column('ghl_oauth_tokens', 'raw_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('ghl_oauth_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ghl_oauth_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('ghl_oauth_tokens_ghl_location_id_key', 'ghl_oauth_tokens', type_='unique')
    op.create_index(op.f('ix_ghl_oauth_tokens_expires_at'), 'ghl_oauth_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_ghl_oauth_tokens_ghl_location_id'), 'ghl_oauth_tokens', ['ghl_location_id'], unique=True)
    op.drop_constraint('ghl_users_ghl_user_id_key', 'ghl_users', type_='unique')
    op.drop_index('idx_ghl_users_user_id', table_name='ghl_users')
    op.create_index(op.f('ix_ghl_users_ghl_location_id'), 'ghl_users', ['ghl_location_id'], unique=False)
    op.create_index(op.f('ix_ghl_users_ghl_user_id'), 'ghl_users', ['ghl_user_id'], unique=True)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_messages_campaign_response', table_name='messages')
    op.drop_index('idx_messages_campaign_sent', table_name='messages')
    op.drop_index('idx_messages_first_response', table_name='messages')
    op.drop_index('idx_messages_has_response', table_name='messages')
    op.drop_index('idx_messages_sent_at', table_name='messages')
    op.drop_index('idx_messages_ghl_message_id', table_name='messages', postgresql_where='(ghl_message_id IS NOT NULL)')
    op.create_index('idx_messages_ghl_message_id', 'messages', ['ghl_message_id'], unique=False)
    op.create_index('idx_messages_ghl_status', 'messages', ['ghl_status'], unique=False)
    op.create_index(op.f('ix_messages_campaign_id'), 'messages', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_messages_ghl_conversation_id'), 'messages', ['ghl_conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_ghl_message_id'), 'messages', ['ghl_message_id'], unique=True)
    op.create_index(op.f('ix_messages_ghl_status'), 'messages', ['ghl_status'], unique=False)
    op.create_index(op.f('ix_messages_recipient_phone'), 'messages', ['recipient_phone'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.drop_column('messages', 'has_response')
    op.drop_column('messages', 'last_response_at')
    op.drop_column('messages', 'response_count')
    op.drop_column('messages', 'response_time_seconds')
    op.drop_column('messages', 'first_response_at')
    op.alter_column('processed_webhooks', 'processed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_processed_webhooks_ghl_location_id'), 'processed_webhooks', ['ghl_location_id'], unique=False)
    op.create_index(op.f('ix_processed_webhooks_processed_at'), 'processed_webhooks', ['processed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_webhooks_processed_at'), table_name='processed_webhooks')
    op.drop_index(op.f('ix_processed_webhooks_ghl_location_id'), table_name='processed_webhooks')
    op.alter_column('processed_webhooks', 'processed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('messages', sa.Column('first_response_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('response_time_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('response_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('last_response_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('has_response', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_recipient_phone'), table_name='messages')
    op.drop_index(op.f('ix_messages_ghl_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_ghl_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_ghl_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_campaign_id'), table_name='messages')
    op.drop_index('idx_messages_ghl_status', table_name='messages')
    op.drop_index('idx_messages_ghl_message_id', table_name='messages')
    op.create_index('idx_messages_ghl_message_id', 'messages', ['ghl_message_id'], unique=False, postgresql_where='(ghl_message_id IS NOT NULL)')
    op.create_index('idx_messages_sent_at', 'messages', ['sent_at'], unique=False)
    op.create_index('idx_messages_has_response', 'messages', ['has_response'], unique=False)
    op.create_index('idx_messages_first_response', 'messages', ['first_response_at'], unique=False)
    op.create_index('idx_messages_campaign_sent', 'messages', ['campaign_id', sa.text('sent_at DESC')], unique=False)
    op.create_index('idx_messages_campaign_response', 'messages', ['campaign_id', 'has_response'], unique=False)
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ghl_users_ghl_user_id'), table_name='ghl_users')
    op.drop_index(op.f('ix_ghl_users_ghl_location_id'), table_name='ghl_users')
    op.create_index('idx_ghl_users_user_id', 'ghl_users', ['ghl_user_id'], unique=False)
    op.create_unique_constraint('ghl_users_ghl_user_id_key', 'ghl_users', ['ghl_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_ghl_oauth_tokens_ghl_location_id'), table_name='ghl_oauth_tokens')
    op.drop_index(op.f('ix_ghl_oauth_tokens_expires_at'), table_name='ghl_oauth_tokens')
    op.create_unique_constraint('ghl_oauth_tokens_ghl_location_id_key', 'ghl_oauth_tokens', ['ghl_location_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('ghl_oauth_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ghl_oauth_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ghl_oauth_tokens', 'raw_response',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('ghl_oauth_tokens', 'token_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Bearer'::character varying"))
    op.drop_index(op.f('ix_ghl_locations_ghl_location_id'), table_name='ghl_locations')
    op.drop_index(op.f('ix_ghl_locations_company_id'), table_name='ghl_locations')
    op.create_unique_constraint('ghl_locations_ghl_location_id_key', 'ghl_locations', ['ghl_location_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('ghl_locations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ghl_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ghl_locations', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('ghl_locations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('ghl_locations', 'has_whatsapp',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_ghl_conversations_ghl_location_id'), table_name='ghl_conversations')
    op.drop_index(op.f('ix_ghl_conversations_ghl_conversation_id'), table_name='ghl_conversations')
    op.drop_index(op.f('ix_ghl_conversations_ghl_contact_id'), table_name='ghl_conversations')
    op.drop_index(op.f('ix_ghl_conversations_contact_phone'), table_name='ghl_conversations')
    op.drop_constraint('idx_ghl_conversations_unique', 'ghl_conversations', type_='unique')
    op.create_index('idx_ghl_conversations_unique', 'ghl_conversations', ['ghl_location_id', 'ghl_contact_id'], unique=False)
    op.create_unique_constraint('ghl_conversations_ghl_conversation_id_key', 'ghl_conversations', ['ghl_conversation_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('ghl_conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ghl_conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ghl_conversations', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('ghl_conversations', 'unread_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_ghl_user_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_ghl_location_id'), table_name='campaigns')
    op.drop_index('idx_campaigns_created_at', table_name='campaigns')
    op.create_index('idx_campaigns_created_at', 'campaigns', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_campaigns_user', 'campaigns', ['ghl_user_id'], unique=False)
    op.create_index('idx_campaigns_scheduled', 'campaigns', ['scheduled_time', 'status'], unique=False, postgresql_where='(scheduled_time IS NOT NULL)')
    op.create_index('idx_campaigns_ghl_user', 'campaigns', ['ghl_user_id'], unique=False)
    op.alter_column('campaigns', 'scheduled_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp for scheduled campaign execution (NULL for immediate campaigns)',
               existing_nullable=True)
    op.alter_column('campaigns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('campaigns', 'messages_template')
    op.drop_column('campaigns', 'contacts_data')
    # ### end Alembic commands ###
